### ISSUE TITLE
Python 2.7 can't run Taiba so far

### ISSUE THREAD

**Issue by school510587** [fann1993814/Taiba#1]
Python 2.7 can't run Taiba with the following testcase:

import Taiba

seg_list = Taiba.lcut(u"Unicode 特殊編碼「突兀」", CRF=False)
print "CRF Disable: " + "/ ".join(seg_list)

Perhaps get_module_res has some problem. Actually, model_path is not a "path". The error message was:

Traceback (most recent call last):
  File "test.py", line 8, in <module>
    seg_list = Taiba.lcut(u"Unicode 特殊編碼「突兀」", CRF=False)
  File "D:\Taiba\Taiba__init__.py", line 378, in lcut
    return list(self.cut(sentence, POS, CRF))
  File "D:\Taiba\Taiba__init__.py", line 322, in cut
    for word in cut_block(blk):
  File "D:\Taiba\Taiba__init__.py", line 236, in **cut_DAG_NO_CRF
    DAG = self.get_DAG(sentence)
  File "D:\Taiba\Taiba__init**.py", line 218, in get_DAG
    self.check_initialized()
  File "D:\Taiba\Taiba__init__.py", line 207, in check_initialized
    self.initialize()
  File "D:\Taiba\Taiba__init__.py", line 198, in initialize
    self.CRFseg = Segment.CRFseg()
  File "D:\Taiba\Taiba\Segment__init__.py", line 13, in **init**
    self.model = CRFModel(get_module_res('Segment/CRFseg.pickle'))
  File "D:\Taiba\Taiba\Segment\crf_model.py", line 6, in **init**
    with gzip.open(model_path, 'rb') as fd:
  File "C:\Python27\lib\gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "C:\Python27\lib\gzip.py", line 94, in **init**
    fileobj = self.myfileobj = **builtin**.open(filename, mode or 'rb')
TypeError: coercing to Unicode: need string or buffer, file found

**Comment by fann1993814** [comment]
TypeError: coercing to Unicode: need string or buffer, file found
Since the file _compat.py
function "get_module_res" in python 2 will return a object, not a filename.

Howerver the default protocol is different between python2 and python3.
python 2 is supported 0(default), 1, 2
python 2 is supported 0, 1, 2, 3(default), 4, 5

**Comment by fann1993814** [comment]
This issue should be fixed. Please checkout commit f10315cab81bf1f2089e75297a5bad761476d8eb
